// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgw21ZIWcwiXFDKzKbkcgjygSI3NDEJfs',
    appId: '1:47390662133:web:63e39ebd40b94e20b954bc',
    messagingSenderId: '47390662133',
    projectId: 'vocab-forge-78557',
    authDomain: 'vocab-forge-78557.firebaseapp.com',
    storageBucket: 'vocab-forge-78557.firebasestorage.app',
    measurementId: 'G-KPMTNLN6R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVx0_6Rwct6wdye3hDU6SjnuPVJYxhhBM',
    appId: '1:47390662133:android:c665862b6b671419b954bc',
    messagingSenderId: '47390662133',
    projectId: 'vocab-forge-78557',
    storageBucket: 'vocab-forge-78557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLl-3rjIyNCcJfbaxKzT8b9KabT7yt5js',
    appId: '1:47390662133:ios:0bfc5ae6deeec948b954bc',
    messagingSenderId: '47390662133',
    projectId: 'vocab-forge-78557',
    storageBucket: 'vocab-forge-78557.firebasestorage.app',
    iosBundleId: 'com.example.vocabForge',
  );

}